// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
///
///
///
///

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsVLC-NI7NXz4CjeBRABER3Ld5c7fL1po',
    appId: '1:617043057768:web:80d7cc2573c379c55d6fdd',
    messagingSenderId: '617043057768',
    projectId: 'flutter-5730e',
    authDomain: 'flutter-5730e.firebaseapp.com',
    storageBucket: 'flutter-5730e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhuaG9BqDwDasC5Ay2oy6_j-23nlVIyU4',
    appId: '1:617043057768:android:d8bd78e24750fa6d5d6fdd',
    messagingSenderId: '617043057768',
    projectId: 'flutter-5730e',
    storageBucket: 'flutter-5730e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLi7INfGoteVWpZ0J3c8nw5yX2PlCZcys',
    appId: '1:617043057768:ios:2902d61b420cc50a5d6fdd',
    messagingSenderId: '617043057768',
    projectId: 'flutter-5730e',
    storageBucket: 'flutter-5730e.appspot.com',
    iosBundleId: 'Robin.Do',
  );
}
